- name: "Run all role tasks for Linux"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_tmux_config_file_path: "{{ linux_tmux_config_file_path }}"
  when: ansible_system == "Linux"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_tmux_config_file_path: "{{ freebsd_tmux_config_file_path }}"
  when: ansible_os_family == "FreeBSD"

