- name: "Run all role tasks for Linux"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_dot_desktop_files_dir: "{{ linux_dot_desktop_files_dir }}"
  when: ansible_system == "Linux"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_dot_desktop_files_dir: "{{ freebsd_dot_desktop_files_dir }}"
  when: ansible_os_family == "FreeBSD"

