# user-specific main tmux config file path
tmux_user_config_file_path: "/home/{{ tmux_user_name }}/.tmux.conf"

# See tmux docs for list of key names:
#   https://github.com/tmux/tmux/wiki/Modifier-Keys

# tmux prefix: type this first, to start sending key-presses to tmux
keymap_prefix: 'C-Space'

