- name: "Configure all tmux settings for user {{ tmux_user_name }}"
  ansible.builtin.include_tasks: settings/main.yml

- name: "Configure user-specified terminal and program tmux launchers"
  ansible.builtin.include_tasks: integrations/main.yml

