- name: "Create tmux_cmd_start_session_in_term_emulator var, export for other roles"
  ansible.builtin.include_tasks: start_session_in_term.yml
  when: export_start_tmux_term_session_cmd

- name: "Create 'start_xxxx_in_tmux' terminal commands and dot-desktop launchers"
  ansible.builtin.include_tasks: start_session_prog.yml
  vars:
    prog_name: "{{ user_prog.name }}"
    prog_cli: "{{ user_prog.cli }}"
    prog_file_basename: "start_{{ prog_name }}_in_tmux"
    create_dot_desktop_launcher: "{{ user_prog.dot_desktop_launcher }}"
    persist_session_on_detach: "{{ user_prog.persist_session }}"
  loop: "{{ create_start_tmux_session_prog_in_term_cmd }}"
  loop_control:
    loop_var: user_prog

