- name: "Create tmux utility scripts directory"
  ansible.builtin.include_tasks: scripts_dir.yml

- name: "Create tmux_cmd_start_session_in_term_emulator var, export for other roles"
  ansible.builtin.include_tasks: start_session_in_term.yml
  when: export_start_tmux_term_session_cmd

- name: "Create 'start_xxxx_in_tmux.desktop' files, for user-specified progs"
  ansible.builtin.include_tasks: start_session_prog_in_term.yml
  loop: "{{ create_start_tmux_session_prog_in_term_dot_deskop_file }}"
  loop_control:
    loop_var: user_prog

