- name: "Create user '{{ script_name }}' script"
  ansible.builtin.template:
    dest: "{{ tmux_utility_script_dir }}/{{ script_name }}"
    src: "start_session_prog_in_term_sh.j2"
    owner: 'root'
    mode: '755'
    force: yes
  become: true
  become_user: root

