- name: "Create utility script: '{{ script_path }}'"
  ansible.builtin.template:
    dest: "{{ script_path }}"
    src: "start_session_prog_in_term_sh.j2"
    owner: "{{ tmux_user_name }}"
    mode: '755'
    force: yes
  become: true
  become_user: root

- name: "Create dot-desktop-file launcher: '{{ dot_desktop_path }}'"
  ansible.builtin.template:
    dest: "{{ dot_desktop_path }}"
    src: "start_session_prog_in_term_desktop.j2"
    owner: 'root'
    mode: '644'
    force: yes
  become: true
  become_user: root

