- name: "Create utility script: '{{ script_path }}'"
  ansible.builtin.template:
    dest: "{{ script_path }}"
    src: "start_session_in_term_sh.j2"
    owner: "{{ tmux_user_name }}"
    mode: '755'
    force: true
  vars:
    script_path: "{{ system_executables_dir }}/start_session_in_term.sh"
  become: true
  become_user: root

- name: "Export cmd as var, for other roles: tmux_cmd_start_session_in_term_emulator"
  ansible.builtin.set_fact:
    tmux_cmd_start_session_in_term_emulator: >-
      {{ tmux_cmd_start_term_emulator }}
      {{ tmux_cmd_term_emulator_exec_arg }}'{{ system_executables_dir }}/start_session_in_term.sh'

